name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
    - ".github/workflows/app_python.yml"
    - "app_python/**"

jobs:
  build:
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./app_python

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Run linter
        run: flake8 .

      - name: Run tests
        run: python -m unittest ./tests/test_*.py

  docker:
    needs: build
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./app_python

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./app_python
          file: ./app_python/distroless.Dockerfile
          push: true
          tags: gendiro/moscow-time-distroless:latest
